# Euler 1

# If we list all the natural numbers below 10
# that are multiples of 3 or 5, we get 3, 5, 6
# and 9. The sum of these multiples is 23.

# Find the sum of all the multiples of 3 or 5 
# below 1000.

/+×↥∩(=0)◿5∶◿3..⇡1000
/+×↥∩(=0)⊃(◿5)(◿3).⇡1000
# /+⊚/↥=0≑∸⋄◿5_3⇡1000 # level id deprecated now
/+⊚/↥=0≡◿5_3¤⇡1000
/+⊚/↥=0⊠◿3_5⇡1000 # without ¤

# with triangular numbers
/+×÷2×+1.⌊÷,999 3_5_¯15
